### ISSUE TITLE
Allow `text_to_snake_case` to be opt-out on `id_` creation

### ISSUE THREAD

**Issue by HASPIMA** [ouhammmourachid/mermaid-py#98]
Whenever creating an instance of a flowchart `Node`, the id provided by the user is forced to be snake case, which this can prevent many issues, but some others may arise. For example, I'm trying to make a tree, which has some constraints that the variables must satisfy. This is the desired output:

```mmd
---
title: Constraint Satisfaction Problem
---
flowchart TB
	.F_(("F"))
	.F_0.x3_(("x3"))
	valid("Valid State")
	.F_0.x3.err_-1754910954858582633("Constraint failed: F == x3")
	.F_(("F"))
	.F_1.x3_(("x3"))
	.F_1.x3.err_-1754910954858582633("Constraint failed: F == x3")
	valid("Valid State")
	.F_1.x3_ -->|3| .F_1.x3.err_-1754910954858582633
	.F_1.x3_ -->|2| .F_1.x3.err_-1754910954858582633
	.F_1.x3_ -->|1| valid
	.F_1.x3_ -->|0| .F_1.x3.err_-1754910954858582633
	.F_ -->|1| .F_1.x3_
	.F_0.x3_ -->|3| .F_0.x3.err_-1754910954858582633
	.F_0.x3_ -->|2| .F_0.x3.err_-1754910954858582633
	.F_0.x3_ -->|1| .F_0.x3.err_-1754910954858582633
	.F_0.x3_ -->|0| valid
	.F_ -->|0| .F_0.x3_

```
Here's a [link to the mermaid live editor](https://mermaid.live/edit#pako:eNqlU11PwjAU_SvNfZKELe26D9YEH9TwZmKC8cE0IZV10ri1pBQFgf9uGZBMiYqYPWw9955zz8ldVzA2hQQGQRBw7ZSrJEPXRs-cFUo7NBROzUoxdspodGfNUyVrrpvmsjJv44mwDt1fcc1dOBhdXHAYcOh09mccLmgDLugBfRWVKjzysH2joRNO-lKrP5TWjgKSJXFOcJ7EvcQ_UUqpJ7WMlUJVsmBogPp91Mh_44Ece9ij_5r0Y45mJgqCyzVdo9-mHXGiMzhkjRpHRwV8sthB50Bv77CVBZ8ghb9k-RuHnMHBn_O3ouNdFuhCLW0tVOF_9hXXCHFwE1n7rTH_WQj7woHrje8Tc2eGSz0G5uxcdmE-Lfx2b5R4tqIGVopq5tGp0MBWsADWC1NMUpL1CCUE0yTqwhJYSsIsThOcZDSjOE7zTRfejfECOMwj357HvpLFUYo9QRbKGXu7u4vNlWwmPDaErY3NB41UD3s) which contains the previous code. This is the generated diagram from the previous code, as you can see we can make us of dots (`.`) and dashes (`-`) in the node identifiers.

[![](https://mermaid.ink/img/pako:eNqlU11PwjAU_SvNfZKELe26D9YEH9TwZmKC8cE0IZV10ri1pBQFgf9uGZBMiYqYPWw9955zz8ldVzA2hQQGQRBw7ZSrJEPXRs-cFUo7NBROzUoxdspodGfNUyVrrpvmsjJv44mwDt1fcc1dOBhdXHAYcOh09mccLmgDLugBfRWVKjzysH2joRNO-lKrP5TWjgKSJXFOcJ7EvcQ_UUqpJ7WMlUJVsmBogPp91Mh_44Ece9ij_5r0Y45mJgqCyzVdo9-mHXGiMzhkjRpHRwV8sthB50Bv77CVBZ8ghb9k-RuHnMHBn_O3ouNdFuhCLW0tVOF_9hXXCHFwE1n7rTH_WQj7woHrje8Tc2eGSz0G5uxcdmE-Lfx2b5R4tqIGVopq5tGp0MBWsADWC1NMUpL1CCUE0yTqwhJYSsIsThOcZDSjOE7zTRfejfECOMwj357HvpLFUYo9QRbKGXu7u4vNlWwmPDaErY3NB41UD3s?type=png)](https://mermaid.live/edit#pako:eNqlU11PwjAU_SvNfZKELe26D9YEH9TwZmKC8cE0IZV10ri1pBQFgf9uGZBMiYqYPWw9955zz8ldVzA2hQQGQRBw7ZSrJEPXRs-cFUo7NBROzUoxdspodGfNUyVrrpvmsjJv44mwDt1fcc1dOBhdXHAYcOh09mccLmgDLugBfRWVKjzysH2joRNO-lKrP5TWjgKSJXFOcJ7EvcQ_UUqpJ7WMlUJVsmBogPp91Mh_44Ece9ij_5r0Y45mJgqCyzVdo9-mHXGiMzhkjRpHRwV8sthB50Bv77CVBZ8ghb9k-RuHnMHBn_O3ouNdFuhCLW0tVOF_9hXXCHFwE1n7rTH_WQj7woHrje8Tc2eGSz0G5uxcdmE-Lfx2b5R4tqIGVopq5tGp0MBWsADWC1NMUpL1CCUE0yTqwhJYSsIsThOcZDSjOE7zTRfejfECOMwj357HvpLFUYo9QRbKGXu7u4vNlWwmPDaErY3NB41UD3s)
But instead I get this by using the library:
```mmd
---
title: Constraint Satisfaction Problem
---
flowchart TB
	_f_(("F"))
	_f_0_x3_(("x3"))
	valid("Valid State")
	_f_0_x3_err__1754910954858582633("Constraint failed: F == x3")
	_f_(("F"))
	_f_1_x3_(("x3"))
	_f_1_x3_err__1754910954858582633("Constraint failed: F == x3")
	valid("Valid State")
	_f_1_x3_ -->|3| _f_1_x3_err__1754910954858582633
	_f_1_x3_ -->|2| _f_1_x3_err__1754910954858582633
	_f_1_x3_ -->|1| valid
	_f_1_x3_ -->|0| _f_1_x3_err__1754910954858582633
	_f_ -->|1| _f_1_x3_
	_f_0_x3_ -->|3| _f_0_x3_err__1754910954858582633
	_f_0_x3_ -->|2| _f_0_x3_err__1754910954858582633
	_f_0_x3_ -->|1| _f_0_x3_err__1754910954858582633
	_f_0_x3_ -->|0| valid
	_f_ -->|0| _f_0_x3_
```

So, I need to _preserve_ the dots because of how I'm traversing the search space, the dots (`.`) allow me to detect how deep in the tree I am and the underscores (`_`) allow me to know the value of the branch itself which I'm currently on, but I lose all of that information because of the resulting code:

https://github.com/ouhammmourachid/mermaid-py/blob/9914ed16e6cd51a8f6eb7a83de44a0a4ba208b6a/mermaid/flowchart/node.py#L75

One way could be creating an optional boolean argument for the constructor (this way could be backwards compatible which is much preferred), or another is to modify the regex to allow dots (`.`) and dashes (`-`). This regex is found here:

https://github.com/ouhammmourachid/mermaid-py/blob/9914ed16e6cd51a8f6eb7a83de44a0a4ba208b6a/mermaid/_utils.py#L44-L45

This regex could be modified to allow `.` and `-`, like so:
```py
    # Remove non-alphanumeric characters except underscores, dots and dashes and replace everything else with underscores
    out: str = re.sub(r'[^a-zA-Z0-9_\.-]', '_', text)
```

I could open a PR, by allowing users to opt-out from the conversion made by `text_to_snake_case` in the constructor `Node`, just so the user can override this behavior (at their own risk). Or just modify the regular expression, this wouldn't be backwards compatible, but it'd work too. 

Let me know what you think and what would work best for this project, I fixed it locally, but still, I think this could improve the usability of this library. Thank you for creating this library, it has helped me a lot!

Hope to hear back from you @ouhammmourachid 😄

**Comment by ouhammmourachid** [comment]
Dear @HASPIMA ,

Thank you for reaching out and providing valuable feedback on the library. I truly appreciate your detailed explanation of the issue you encountered and the proposed solutions to address it.

After carefully considering your suggestions, I agree that modifying the regular expression to allow dots (.) and dashes (-) would be a beneficial enhancement to the library. This change would enable users to maintain the desired structure of their node identifiers without losing important information during the conversion process.

Moreover, I believe that this adjustment will not cause any compatibility issues as it expands the range of characters allowed in node identifiers while preserving the existing functionality for users who prefer snake case format.

**Comment by HASPIMA** [comment]
Hey @ouhammmourachid, thank you for your insightful feedback. After evaluating what we said, I agree #99 would be a better solution candidate for this issue, in the meantime I'll be closing #100 referencing this comment.

Thanks so much for your quick response, I'll keep on finishing #99 just so we can have this issue fixed. Ohh, more thing, can you add this repository to the [PyPi project](https://pypi.org/project/mermaid-py/), it took me longer than expected to find this repo heheh, that'll be much appreciated. Have a good one!
